# Generated by Django 4.2.4 on 2023-12-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(default=8),
        ),
    ]
