# Generated by Django 4.2.4 on 2023-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movies_description_alter_movies_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
